// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Additional palettes for PaletteFx. See:
// https://getreuer.info/posts/keyboards/palettefx/index.html#make-your-own-palettes
{  // Mecha palette.
  HSV16(186, 238, 187),
  HSV16(184, 221, 204),
  HSV16(185, 204, 204),
  HSV16(187, 187, 221),
  HSV16(190, 187, 221),
  HSV16(193, 170, 238),
  HSV16(195, 153, 238),
  HSV16(197, 119, 221),
  HSV16(200,  68, 204),
  HSV16(237,  17, 170),
  HSV16( 57, 153, 204),
  HSV16( 60, 255, 238),
  HSV16( 62, 255, 238),
  HSV16( 61, 255, 238),
  HSV16( 57, 255, 255),
  HSV16( 61, 136, 255),
},
{  // Hero palette.
  HSV16(166, 238, 153),
  HSV16(160, 238, 170),
  HSV16(152, 255, 187),
  HSV16(147, 255, 221),
  HSV16(145, 255, 238),
  HSV16(143, 255, 255),
  HSV16(145, 204, 255),
  HSV16(145, 119, 255),
  HSV16(111,  34, 221),
  HSV16( 41, 153, 238),
  HSV16( 38, 238, 255),
  HSV16( 38, 119, 255),
  HSV16( 42,  17, 255),
  HSV16( 45,   0, 255),
  HSV16( 43,   0, 255),
  HSV16( 43,   0, 255),
},
